---@meta

-- Engine functions that ARE registered by GuildII.exe but do not appear in
-- ScriptDocumentation.html. Generated by
-- tools/modding_helpers/gen_engine_bindings.py; do not edit by hand.
--
-- There are no descriptions here on purpose. Nothing in the binary says what
-- these functions mean, and inventing prose would be worse than silence.
-- What IS recovered is mechanical: the native address, the .cpp file and line
-- the binding sits on, how many parameters it reads, each parameter's type,
-- and which are optional.
--
-- Accuracy, measured by running the same recovery against 60 documented natives
-- and comparing with the dump: arity correct 53/60; of 111 parameter positions,
-- 7 genuine type disagreements (6%), and a further 9 where the dump says 'any'
-- and this is more specific; optional flags agree 97/107.
--
-- No @return anywhere: the likeliest return-pusher also correlates with Alias
-- PARAMETERS, so return types cannot be established this way.
--
-- Where no parameter could be read the stub is `(...)`, NOT `()`. Those natives
-- (the CC_* character-creation family and others) use a shorter fetch shape
-- carrying no type descriptor. Declaring them as taking nothing would make the
-- language server flag correct calls as errors, so they accept anything instead.

---@class Alias

---Undocumented. Native at 0x0044ed60
---@param p1 number
---@param p2 number
---@param p3 Alias
function AddAchievementProgress(p1, p2, p3) end

---Undocumented. Native at 0x00451a00
---@param p1 Alias
function ApplyGraphicsSettings(p1) end

---Undocumented. Native at 0x00708030, GuildGameScriptBinding.cpp:15277
---@param p1 Alias
---@param p2 string
function ApplyShader(p1, p2) end

---Undocumented. Native at 0x005cfb30
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function Assert(...) end

---Undocumented. Native at 0x0070c800, GuildGameScriptBinding.cpp:19878
---@param p1 Alias
---@param p2 Alias
function AttachModel(p1, p2) end

---Undocumented. Native at 0x0070c8c0, GuildGameScriptBinding.cpp:20004
---@param p1 Alias
---@param p2 Alias
---@param p3 string
function BlackBoardAddPamphlet(p1, p2, p3) end

---Undocumented. Native at 0x0070cdd0, GuildGameScriptBinding.cpp:20050
---@param p1 Alias
---@param p2 number
function BlackBoardRemovePamphlet(p1, p2) end

---Undocumented. Native at 0x0070d770, GuildGameScriptBinding.cpp:21829
---@param p1 Alias
---@param p2 Alias
function BoardShip(p1, p2) end

---Undocumented. Native at 0x00705db0, GuildGameScriptBinding.cpp:13730
---@param p1 Alias
---@param p2 number
---@param p3 boolean
---@param p4 string
function BuildingBuyCart(p1, p2, p3, p4) end

---Undocumented. Native at 0x00705ff0, GuildGameScriptBinding.cpp:13815
---@param p1 Alias
---@param p2 Alias
function BuildingCanBeOwnedBy(p1, p2) end

---Undocumented. Native at 0x006faf90, GuildGameScriptBinding.cpp:4883
---@param p1 Alias
function BuildingCanHireNewWorker(p1) end

---Undocumented. Native at 0x0070f290, GuildGameScriptBinding.cpp:4671
---@param p1 Alias
---@param p2 Alias
---@param p3 string
function BuildingFindWaterPos(p1, p2, p3) end

---Undocumented. Native at 0x006facd0, GuildGameScriptBinding.cpp:4753
---@param p1 Alias
function BuildingGetBuyPrice(p1) end

---Undocumented. Native at 0x00704170, GuildGameScriptBinding.cpp:12436
---@param p1 Alias
---@param p2 string
function BuildingGetPrisoner(p1, p2) end

---Undocumented. Native at 0x00700c50, GuildGameScriptBinding.cpp:9521
---@param p1 Alias
---@param p2 string
---@param p3 string
function BuildingGetRoom(p1, p2, p3) end

---Undocumented. Native at 0x00712b80, GuildGameScriptBinding.cpp:12366
---@param p1 Alias
---@param p2 boolean
---@param p3 string
function BuildingGetWaterPos(p1, p2, p3) end

---Undocumented. Native at 0x006faff0, GuildGameScriptBinding.cpp:4902
---@param p1 Alias
function BuildingHasIndoor(p1) end

---Undocumented. Native at 0x00702500, GuildGameScriptBinding.cpp:11244
---@param p1 Alias
function BuildingIsWorkingTime(p1) end

---Undocumented. Native at 0x00703f70, GuildGameScriptBinding.cpp:12330
---@param p1 Alias
---@param p2 Alias
---@param p3? Alias
function BuildingSetWaterPos(p1, p2, p3) end

---Undocumented. Native at 0x00450c90
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function CC_Continue(...) end

---Undocumented. Native at 0x00452d30
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function CC_DecrementSkill(...) end

---Undocumented. Native at 0x00450cb0
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function CC_Finish(...) end

---Undocumented. Native at 0x00452840
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function CC_GetClass(...) end

---Undocumented. Native at 0x00452d80
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function CC_GetClassNames(...) end

---Undocumented. Native at 0x00452990
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function CC_GetFirstName(...) end

---Undocumented. Native at 0x004526d0
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function CC_GetGender(...) end

---Undocumented. Native at 0x00452aa0
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function CC_GetLastName(...) end

---Undocumented. Native at 0x004527a0
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function CC_GetReligion(...) end

---Undocumented. Native at 0x00452bc0
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function CC_GetSkills(...) end

---Undocumented. Native at 0x004528f0
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function CC_GetZodiac(...) end

---Undocumented. Native at 0x00450c20
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function CC_GetZodiacNames(...) end

---Undocumented. Native at 0x00452ce0
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function CC_IncrementSkill(...) end

---Undocumented. Native at 0x00452b90
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function CC_RandomName(...) end

---Undocumented. Native at 0x00453080
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function CC_SetBeard(...) end

---Undocumented. Native at 0x004528a0
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function CC_SetClass(...) end

---Undocumented. Native at 0x00452a20
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function CC_SetFirstName(...) end

---Undocumented. Native at 0x00452720
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function CC_SetGender(...) end

---Undocumented. Native at 0x00453030
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function CC_SetHair(...) end

---Undocumented. Native at 0x004530d0
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function CC_SetHairColor(...) end

---Undocumented. Native at 0x00453120
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function CC_SetHat(...) end

---Undocumented. Native at 0x00452b30
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function CC_SetLastName(...) end

---Undocumented. Native at 0x004527f0
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function CC_SetReligion(...) end

---Undocumented. Native at 0x00452fe0
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function CC_SetSkin(...) end

---Undocumented. Native at 0x00453170
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function CC_SetVoice(...) end

---Undocumented. Native at 0x00452950
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function CC_SetZodiac(...) end

---Undocumented. Native at 0x00702910, GuildGameScriptBinding.cpp:11425
---@param p1 Alias
---@param p2 string
---@param p3? number
function CChangeAnimation(p1, p2, p3) end

---Undocumented. Native at 0x00712690, GuildGameScriptBinding.cpp:11563
---@param p1 Alias
---@param p2 string
function CExitCurrentBuilding(p1, p2) end

---Undocumented. Native at 0x006fed40, GuildGameScriptBinding.cpp:7329
---@param p1 Alias
---@param p2 Alias
---@param p3? string
---@param p4? string
function CFight(p1, p2, p3, p4) end

---Undocumented. Native at 0x006fd390, GuildGameScriptBinding.cpp:6598
---@param p1 Alias
---@param p2 Alias
---@param p3? number
---@param p4? string
---@param p5? number
---@param p6? boolean
---@param p7? boolean
function CFollow(p1, p2, p3, p4, p5, p6, p7) end

---Undocumented. Native at 0x0044e850
---@param p1 string
---@param p2 boolean
function CHudRemoveCountdown(p1, p2) end

---Undocumented. Native at 0x00712110, GuildGameScriptBinding.cpp:11003
---@param p1 Alias
---@param p2 number
function CIncrementXP(p1, p2) end

---Undocumented. Native at 0x0044d790
---@param p1 string
---@param p2? string
---@param p3 string
function CInitAlias(p1, p2, p3) end

---Undocumented. Native at 0x0044d580
---@param p1 string
---@param p2 string
---@param p3 string
function CInitData(p1, p2, p3) end

---Undocumented. Native at 0x00702b20, GuildGameScriptBinding.cpp:11514
---@param p1 Alias
---@param p2 string
---@param p3? number
function CLoopAnimation(p1, p2, p3) end

---Undocumented. Native at 0x006fd150, GuildGameScriptBinding.cpp:6518
---@param p1 Alias
---@param p2 Alias
---@param p3? number
---@param p4? string
---@param p5? number
---@param p6 boolean
function CMoveTo(p1, p2, p3, p4, p5, p6) end

---Undocumented. Native at 0x006fd270, GuildGameScriptBinding.cpp:6547
---@param p1 Alias
---@param p2 Alias
---@param p3? number
---@param p4? string
---@param p5? number
---@param p6? boolean
function CMoveToWeak(p1, p2, p3, p4, p5, p6) end

---Undocumented. Native at 0x0044c540
---@param p1 string
---@param p2 Alias
---@param p3 string
---@param p4 boolean
---@param p5 string
---@param p6 string
function CMsgBox(p1, p2, p3, p4, p5, p6) end

---Undocumented. Native at 0x0070a290, GuildGameScriptBinding.cpp:17466
---@param p1 string
---@param p2? Alias
---@param p3? string
---@param p4 boolean
---@param p5 string
---@param p6? number
---@param p7? string
---@param p8? string
function CMsgNews(p1, p2, p3, p4, p5, p6, p7, p8) end

---Undocumented. Native at 0x0044c9f0
---@param p1? Alias
---@param p2? Alias
---@param p3 string
---@param p4 boolean
---@param p5 string
---@param p6 string
function CMsgQuest(p1, p2, p3, p4, p5, p6) end

---Undocumented. Native at 0x0044cb20
---@param p1? string
function CMsgQuestIntro(p1) end

---Undocumented. Native at 0x0070a5d0, GuildGameScriptBinding.cpp:17658
---@param p1? Alias
---@param p2 Alias
---@param p3? Alias
---@param p4? string
---@param p5 boolean
---@param p6 string
function CMsgSay(p1, p2, p3, p4, p5, p6) end

---Undocumented. Native at 0x00702820, GuildGameScriptBinding.cpp:11388
---@param p1 Alias
---@param p2 string
---@param p3? number
---@param p4? number
function CPlayAnimation(p1, p2, p3, p4) end

---Undocumented. Native at 0x00638790, GamebaseScriptBinding.cpp:691
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function CSendCommand(...) end

---Undocumented. Native at 0x0063a3d0
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function CShowPanel(...) end

---Undocumented. Native at 0x0044e1e0
---@param p1 number
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 boolean
---@param p7 string
---@param p8 string
---@param p9 string
---@param p10 string
---@param p11 number
function CShowTutorialBox(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11) end

---Undocumented. Native at 0x00702d80, GuildGameScriptBinding.cpp:11654
---@param p1 Alias
---@param p2 number
---@param p3 number
---@param p4? string
function CStroll(p1, p2, p3, p4) end

---Undocumented. Native at 0x006ff630, GuildGameScriptBinding.cpp:7866
---@param p1 Alias
---@param p2? number
function CUseLocator(p1, p2) end

---Undocumented. Native at 0x00638a20, GamebaseScriptBinding.cpp:737
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function CWaitForSelection(...) end

---Undocumented. Native at 0x00802c00, CameraScriptBinding.cpp:473
---@param p1 boolean
function CameraEnableUserUnlock(p1) end

---Undocumented. Native at 0x00802600, CameraScriptBinding.cpp:102
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function CameraIsLocked(...) end

---Undocumented. Native at 0x00706dc0, GuildGameScriptBinding.cpp:14366
---@param p1 Alias
---@param p2? string
function CartCheckEscort(p1, p2) end

---Undocumented. Native at 0x00706e60, GuildGameScriptBinding.cpp:14395
---@param p1 Alias
function CartCheckFighting(p1) end

---Undocumented. Native at 0x00706ce0, GuildGameScriptBinding.cpp:14323
---@param p1 Alias
function CartCreateEscort(p1) end

---Undocumented. Native at 0x00706c70, GuildGameScriptBinding.cpp:14301
---@param p1 Alias
function CartGetEscortCount(p1) end

---Undocumented. Native at 0x00706d50, GuildGameScriptBinding.cpp:14344
---@param p1 Alias
function CartRemoveEscort(p1) end

---Undocumented. Native at 0x005cbc90
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function Cast(...) end

---Undocumented. Native at 0x004515a0
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function ChangeGameState(...) end

---Undocumented. Native at 0x008013b0, OfficeScriptBinding.cpp:1285
---@param p1 Alias
---@param p2 string
function CityGetChairmanList(p1, p2) end

---Undocumented. Native at 0x007117a0, GuildGameScriptBinding.cpp:10282
---@param p1 Alias
---@param p2 string
function CityGetDynastyCharList(p1, p2) end

---Undocumented. Native at 0x00713820, GuildGameScriptBinding.cpp:15927
---@param p1 Alias
---@param p2 number
---@param p3? number
function CityGetFreeEventHour(p1, p2, p3) end

---Undocumented. Native at 0x00718ad0, GuildGameScriptBinding.cpp:14672
---@param p1 Alias
---@param p2 number
function CityGetItemDemand(p1, p2) end

---Undocumented. Native at 0x007115f0, GuildGameScriptBinding.cpp:10231
---@param p1 Alias
function CityGetNumEvents(p1) end

---Undocumented. Native at 0x008017f0, OfficeScriptBinding.cpp:1194
---@param p1 Alias
---@param p2 string
---@param p3 number
function CityGetOfficeSessionMemberList(p1, p2, p3) end

---Undocumented. Native at 0x006f6110, GuildGameScriptBinding.cpp:1060
---@param p1 Alias
function CityIsKontor(p1) end

---Undocumented. Native at 0x00801500, OfficeScriptBinding.cpp:1332
---@param p1 Alias
---@param p2 string
---@param p3 boolean
function CityPrepareOfficesToVote(p1, p2, p3) end

---Undocumented. Native at 0x008010b0, OfficeScriptBinding.cpp:1064
---@param p1 Alias
---@param p2 Alias
function CityRemoveApplicant(p1, p2) end

---Undocumented. Native at 0x006f63f0, GuildGameScriptBinding.cpp:1193
---@param p1 Alias
---@param p2 number
---@param p3? number
---@param p4? number
---@param p5? number
function CitySetFixedPrice(p1, p2, p3, p4, p5) end

---Undocumented. Native at 0x0044e570
---@param p1 string
function ClearImportantPersonSection(p1) end

---Undocumented. Native at 0x006fefa0, GuildGameScriptBinding.cpp:7423
---@param p1 Alias
function ClearMeasureCache(p1) end

---Undocumented. Native at 0x00702570, GuildGameScriptBinding.cpp:11264
---@param p1 Alias
---@param p2 boolean
function CommandStructure(p1, p2) end

---Undocumented. Native at 0x0044e990
---@param p1 number
---@param p2 Alias
function CompleteAchievement(p1, p2) end

---Undocumented. Native at 0x0044e610
---@param p1 string
---@param p2 string
function CreateImportantPersonSection(p1, p2) end

---Undocumented. Native at 0x006fc010, GuildGameScriptBinding.cpp:5639
---@param p1 number
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5? number
function CreateRoad(p1, p2, p3, p4, p5) end

---Undocumented. Native at 0x006fbe40, GuildGameScriptBinding.cpp:5600
---@param p1 number
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5? number
---@param p6 number
---@param p7 Alias
function CreateWorkOfArt(p1, p2, p3, p4, p5, p6, p7) end

---Undocumented. Native at 0x008022f0, CameraScriptBinding.cpp:785
---@param p1 Alias
---@param p2 Alias
function CutsceneAddSim(p1, p2) end

---Undocumented. Native at 0x007093a0, GuildGameScriptBinding.cpp:16181
---@param p1 Alias
---@param p2 string
function CutsceneCallScheduled(p1, p2) end

---Undocumented. Native at 0x00709480, GuildGameScriptBinding.cpp:16200
---@param p1 Alias
---@param p2 string
function CutsceneCallUnscheduled(p1, p2) end

---Undocumented. Native at 0x00802380, CameraScriptBinding.cpp:801
---@param p1 Alias
---@param p2 Alias
function CutsceneRemoveSim(p1, p2) end

---Undocumented. Native at 0x0044e7c0
---@param p1 Alias
---@param p2 boolean
function CutsceneShowCharacterPanel(p1, p2) end

---Undocumented. Native at 0x00450b40
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function DeleteSaveGame(...) end

---Undocumented. Native at 0x00803920, CameraScriptBinding.cpp:816
---@param p1? Alias
function DestroyCutscene(p1) end

---Undocumented. Native at 0x00450af0
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function DumpFileManifest(...) end

---Undocumented. Native at 0x006f8f60, GuildGameScriptBinding.cpp:3243
---@param p1 Alias
function DynastyAvoidControl(p1) end

---Undocumented. Native at 0x006f96b0, GuildGameScriptBinding.cpp:3590
---@param p1 Alias
---@param p2 number
---@param p3 string
function DynastyGetBuilding2(p1, p2, p3) end

---Undocumented. Native at 0x006f9630, GuildGameScriptBinding.cpp:3564
---@param p1 Alias
---@param p2 number
---@param p3 string
function DynastyGetBuildingCount2(p1, p2, p3) end

---Undocumented. Native at 0x006f8d80, GuildGameScriptBinding.cpp:3190
---@param p1 Alias
---@param p2 Alias
function DynastyGetMaxDiplomacyState(p1, p2) end

---Undocumented. Native at 0x006f8cd0, GuildGameScriptBinding.cpp:3166
---@param p1 Alias
---@param p2 Alias
function DynastyGetMinDiplomacyState(p1, p2) end

---Undocumented. Native at 0x006f82c0, GuildGameScriptBinding.cpp:2814
---@param p1 Alias
function DynastyGetTotalSeaTradeValue(p1) end

---Undocumented. Native at 0x00703d60, GuildGameScriptBinding.cpp:12241
---@param p1 Alias
function DynastyHasUpgrade(p1) end

---Undocumented. Native at 0x006f8220, GuildGameScriptBinding.cpp:2790
---@param p1 Alias
function DynastyIsHumanControlled(p1) end

---Undocumented. Native at 0x007054c0, GuildGameScriptBinding.cpp:13379
---@param p1 Alias
---@param p2 Alias
---@param p3 number
---@param p4 number
---@param p5 number
function GetAccessPriceGive(p1, p2, p3, p4, p5) end

---Undocumented. Native at 0x007053f0, GuildGameScriptBinding.cpp:13353
---@param p1 Alias
---@param p2 Alias
---@param p3 number
---@param p4 number
---@param p5 number
function GetAccessPriceTake(p1, p2, p3, p4, p5) end

---Undocumented. Native at 0x0044eec0
---@param p1 number
---@param p2 Alias
function GetAchievementCategory(p1, p2) end

---Undocumented. Native at 0x0044f1e0
---@param p1 number
---@param p2 Alias
function GetAchievementInfo(p1, p2) end

---Undocumented. Native at 0x0044ebc0
---@param p1 number
---@param p2 Alias
function GetAchievementProgress(p1, p2) end

---Undocumented. Native at 0x0044f090
---@param p1 Alias
function GetAchievementScore(p1) end

---Undocumented. Native at 0x00451870
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function GetConfigFloat(...) end

---Undocumented. Native at 0x00451290
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function GetConfigInt(...) end

---Undocumented. Native at 0x00451370
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function GetConfigString(...) end

---Undocumented. Native at 0x00639c50, GamebaseScriptBinding.cpp:1127
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function GetDatabaseMaxID(...) end

---Undocumented. Native at 0x0070d690, GuildGameScriptBinding.cpp:20331
---@param p1 Alias
function GetDisplayName(p1) end

---Undocumented. Native at 0x004508f0
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function GetDynastyColors(...) end

---Undocumented. Native at 0x00718d70, GuildGameScriptBinding.cpp:17946
---@param p1 Alias
---@param p2 Alias
function GetDynastyEvidenceValues(p1, p2) end

---Undocumented. Native at 0x00711b00, GuildGameScriptBinding.cpp:10539
---@param p1? Alias
---@param p2 Alias
function GetFavor(p1, p2) end

---Undocumented. Native at 0x00450330
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function GetFingerprint(...) end

---Undocumented. Native at 0x00450210
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function GetGameVersion(...) end

---Undocumented. Native at 0x00711990, GuildGameScriptBinding.cpp:10384
---@param p1 Alias
function GetHoursToNextTrial(p1) end

---Undocumented. Native at 0x00703c20, GuildGameScriptBinding.cpp:12196
---@param p1 Alias
---@param p2? number
---@param p3 string
function GetInventory(p1, p2, p3) end

---Undocumented. Native at 0x004503c0
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function GetLocalizedText(...) end

---Undocumented. Native at 0x00450750
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function GetMapInfo(...) end

---Undocumented. Native at 0x00450560
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function GetMapList(...) end

---Undocumented. Native at 0x00715920, GuildGameScriptBinding.cpp:20169
---@param p1 Alias
---@param p2 string
function GetMount(p1, p2) end

---Undocumented. Native at 0x00801660, OfficeScriptBinding.cpp:1495
---@param p1 Alias
---@param p2 string
---@param p3 number
function GetOfficeByApplicant(p1, p2, p3) end

---Undocumented. Native at 0x00450370
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function GetPlayerName(...) end

---Undocumented. Native at 0x006fb940, GuildGameScriptBinding.cpp:5336
---@param p1 Alias
function GetPositionXYZ(p1) end

---Undocumented. Native at 0x00717fe0, GuildGameScriptBinding.cpp:9472
---@param p1 string
function GetRandomPlayerDynasty(p1) end

---Undocumented. Native at 0x00451dc0
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function GetSaveGameList(...) end

---Undocumented. Native at 0x00453370
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function GetScreenModes(...) end

---Undocumented. Native at 0x00716e00, GuildGameScriptBinding.cpp:16763
---@param p1 Alias
---@param p2? number
---@param p3 string
---@param p4? number
function GetSimsInRange(p1, p2, p3, p4) end

---Undocumented. Native at 0x0070d2b0, GuildGameScriptBinding.cpp:20273
---@param p1 string
---@param p2 string
function GetStat(p1, p2) end

---Undocumented. Native at 0x005cbd80
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function GetValueFloat(...) end

---Undocumented. Native at 0x005cbd00
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function GetValueInt(...) end

---Undocumented. Native at 0x005cc6b0
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function GetValueString(...) end

---Undocumented. Native at 0x006fc130, GuildGameScriptBinding.cpp:5664
---@param p1 Alias
---@param p2 number
---@param p3? number
function GetWorkOfArtData(p1, p2, p3) end

---Undocumented. Native at 0x006fb7f0, GuildGameScriptBinding.cpp:5308
---@param p1 Alias
function GetWorldPositionXYZ(p1) end

---Undocumented. Native at 0x006fe6e0, GuildGameScriptBinding.cpp:7090
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function GetYear(...) end

---Undocumented. Native at 0x0044f330
---@param p1 string
function GuideSetPage(p1) end

---Undocumented. Native at 0x00451450
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function HidePanel(...) end

---Undocumented. Native at 0x0044e900
---@param p1 string
function HudGetSelectionCount(p1) end

---Undocumented. Native at 0x00713380, GuildGameScriptBinding.cpp:15104
---@param p1 Alias
---@param p2 any
---@param p3 number
function IncrementSkillValue(p1, p2, p3) end

---Undocumented. Native at 0x0070c2d0, GuildGameScriptBinding.cpp:19503
---@param p1 Alias
---@param p2 number
---@param p3? number
function InventoryGetSlotSize(p1, p2, p3) end

---Undocumented. Native at 0x0044ecb0
---@param p1 number
---@param p2 Alias
function IsAchievementCompleted(p1, p2) end

---Undocumented. Native at 0x0044f130
---@param p1 number
---@param p2 Alias
function IsAchievementUnlocked(p1, p2) end

---Undocumented. Native at 0x0070d1e0, GuildGameScriptBinding.cpp:20215
---@param p1 string
function IsAchievementVanillaOnly(p1) end

---Undocumented. Native at 0x0044e160
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function IsDemo(...) end

---Undocumented. Native at 0x0070d1b0, GuildGameScriptBinding.cpp:20206
---@param p1 string
function IsModActive(p1) end

---Undocumented. Native at 0x0070d0e0, GuildGameScriptBinding.cpp:20126
---@param p1 Alias
function IsMount(p1) end

---Undocumented. Native at 0x00715760, GuildGameScriptBinding.cpp:20107
---@param p1 Alias
function IsMounted(p1) end

---Undocumented. Native at 0x007051a0, GuildGameScriptBinding.cpp:13262
---@param p1 Alias
---@param p2 string
function IsTypeExact(p1, p2) end

---Undocumented. Native at 0x00707400, GuildGameScriptBinding.cpp:14609
---@param p1 number
function ItemGetNeed(p1) end

---Undocumented. Native at 0x006fd880, GuildGameScriptBinding.cpp:6793
---@param p1 number
function KontorFreezeAll(p1) end

---Undocumented. Native at 0x006fe4a0, GuildGameScriptBinding.cpp:7030
---@param p1 Alias
---@param p2 number
function KontorGetLordPermitLeft(p1, p2) end

---Undocumented. Native at 0x006fd9f0, GuildGameScriptBinding.cpp:6822
---@param p1 Alias
---@param p2 number
function KontorGetPermitLeft(p1, p2) end

---Undocumented. Native at 0x006fe370, GuildGameScriptBinding.cpp:7011
---@param p1 Alias
---@param p2 number
---@param p3 number
function KontorGrantLordPermit(p1, p2, p3) end

---Undocumented. Native at 0x006fd8c0, GuildGameScriptBinding.cpp:6803
---@param p1 Alias
---@param p2 number
---@param p3 number
function KontorGrantPermit(p1, p2, p3) end

---Undocumented. Native at 0x006fdc60, GuildGameScriptBinding.cpp:6884
---@param p1 number
---@param p2 number
function KontorPublishFactory(p1, p2) end

---Undocumented. Native at 0x006fe020, GuildGameScriptBinding.cpp:6940
---@param p1 Alias
---@param p2? number
function KontorSetCharterLord(p1, p2) end

---Undocumented. Native at 0x006fe0b0, GuildGameScriptBinding.cpp:6956
---@param p1 Alias
---@param p2 number
---@param p3 number
function KontorSetLordship(p1, p2, p3) end

---Undocumented. Native at 0x006fdb10, GuildGameScriptBinding.cpp:6840
---@param p1 Alias
---@param p2 number
---@param p3? string
---@param p4? string
---@param p5? string
function KontorSetRealmLabels(p1, p2, p3, p4, p5) end

---Undocumented. Native at 0x006fdf20, GuildGameScriptBinding.cpp:6920
---@param p1 Alias
---@param p2 number
---@param p3 number
---@param p4 number
function KontorSetReroll(p1, p2, p3, p4) end

---Undocumented. Native at 0x006fd740, GuildGameScriptBinding.cpp:6770
---@param p1 Alias
---@param p2 number
---@param p3 number
---@param p4 number
function KontorSetRoute(p1, p2, p3, p4) end

---Undocumented. Native at 0x0044cd30
---@param p1? Alias
---@param p2? Alias
function KontorShowPrivileges(p1, p2) end

---Undocumented. Native at 0x00710e20, GuildGameScriptBinding.cpp:9256
---@param p1 string
function ListAllCutscenes(p1) end

---Undocumented. Native at 0x00639b00, GamebaseScriptBinding.cpp:1103
---@param p1 Alias
function ListContains(p1) end

---Undocumented. Native at 0x00701a80, GuildGameScriptBinding.cpp:10351
---@param p1 string
function ListCrimeReport(p1) end

---Undocumented. Native at 0x00452530
---@param p1 Alias
function LoadSaveGame(p1) end

---Undocumented. Native at 0x006ff300, GuildGameScriptBinding.cpp:7663
---@param p1 Alias
function LocatorGetBlocker(p1) end

---Undocumented. Native at 0x005cc850
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function LogError(...) end

---Undocumented. Native at 0x005cbe00
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function LogWarning(...) end

---Undocumented. Native at 0x006fe170, GuildGameScriptBinding.cpp:6974
---@param p1 Alias
---@param p2 number
---@param p3 number
function LordshipAddFavor(p1, p2, p3) end

---Undocumented. Native at 0x006fe2b0, GuildGameScriptBinding.cpp:6995
---@param p1 Alias
---@param p2 number
function LordshipGetFavor(p1, p2) end

---Undocumented. Native at 0x005cbac0
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function LuaType(...) end

---Undocumented. Native at 0x007074e0, GuildGameScriptBinding.cpp:14632
---@param p1 Alias
function MarketConsume(p1) end

---Undocumented. Native at 0x00707590, GuildGameScriptBinding.cpp:14655
---@param p1 Alias
---@param p2 number
function MarketRegisterSale(p1, p2) end

---Undocumented. Native at 0x0063cb00, GamebaseScriptBinding.cpp:2537
---@param p1 number
function MeasureSetStopMode(p1) end

---Undocumented. Native at 0x0070cf80, GuildGameScriptBinding.cpp:20075
---@param p1 Alias
function Mount(p1) end

---Undocumented. Native at 0x00712d30, GuildGameScriptBinding.cpp:14435
---@param p1 Alias
function MoveGetPrefPattern(p1) end

---Undocumented. Native at 0x006fd040, GuildGameScriptBinding.cpp:6458
---@param p1 Alias
function MoveGetStance(p1) end

---Undocumented. Native at 0x006fcc30, GuildGameScriptBinding.cpp:6207
---@param p1 Alias
function ObjectGetRotationY(p1) end

---Undocumented. Native at 0x0044de40
---@param p1 Alias
---@param p2 number
---@param p3 number
function OfficeApplicationHUDAddVoter(p1, p2, p3) end

---Undocumented. Native at 0x0044dd60
---@param p1 Alias
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 number
function OfficeApplicationHUDSetCandidates(p1, p2, p3, p4, p5, p6) end

---Undocumented. Native at 0x0044df70
---@param p1 Alias
---@param p2 number
---@param p3 number
function OfficeDepositionHUDAddVoter(p1, p2, p3) end

---Undocumented. Native at 0x0044dee0
---@param p1 Alias
---@param p2 number
function OfficeDepositionHUDSetCandidate(p1, p2) end

---Undocumented. Native at 0x00800140, OfficeScriptBinding.cpp:899
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function OfficeGetChargeCost(...) end

---Undocumented. Native at 0x00800240, OfficeScriptBinding.cpp:1477
---@param p1 Alias
function OfficeGetIdx(p1) end

---Undocumented. Native at 0x00801b60, OfficeScriptBinding.cpp:1379
---@param p1 Alias
---@param p2 string
---@param p3 number
function OfficePrepareSessionMembers(p1, p2, p3) end

---Undocumented. Native at 0x008001b0, OfficeScriptBinding.cpp:1456
---@param p1 Alias
---@param p2 Alias
function OfficeRemoveApplicant(p1, p2) end

---Undocumented. Native at 0x00450a50
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function OpenBugReport(...) end

---Undocumented. Native at 0x0070a170, GuildGameScriptBinding.cpp:17448
---@param p1 Alias
function OpenLetterComposer(p1) end

---Undocumented. Native at 0x00450a20
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function OpenSteamOverlayURL(...) end

---Undocumented. Native at 0x006fa990, GuildGameScriptBinding.cpp:4583
---@param p1 string
function OutputDebugString(p1) end

---Undocumented. Native at 0x006fb330, GuildGameScriptBinding.cpp:5134
---@param p1 Alias
---@param p2 string
function Position2GuildObject(p1, p2) end

---Undocumented. Native at 0x00450360
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function QuitGame(...) end

---Undocumented. Native at 0x006fde40, GuildGameScriptBinding.cpp:6903
---@param p1 number
function RealmGetRuler(p1) end

---Undocumented. Native at 0x006fdd40, GuildGameScriptBinding.cpp:6884
---@param p1 number
---@param p2 Alias
function RealmSetRuler(p1, p2) end

---Undocumented. Native at 0x00704db0, GuildGameScriptBinding.cpp:13028
---@param p1 Alias
function RemoveAllImpactDependendImpacts(p1) end

---Undocumented. Native at 0x0070acb0, GuildGameScriptBinding.cpp:18032
---@param p1 Alias
---@param p2 Alias
function RemoveDynastyEvidences(p1, p2) end

---Undocumented. Native at 0x00505130
---@param p1 any
---@param p2 string
function RenderCustomClear(p1, p2) end

---Undocumented. Native at 0x00505210
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function RenderCustomClearAll(...) end

---Undocumented. Native at 0x00504950
---@param p1 any
---@param p2 string
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 number
---@param p7 number
---@param p8 number
function RenderCustomSetCamera(p1, p2, p3, p4, p5, p6, p7, p8) end

---Undocumented. Native at 0x00504a40
---@param p1 any
---@param p2 string
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 number
---@param p7 number
---@param p8 number
---@param p9? number
function RenderCustomSetFOV(p1, p2, p3, p4, p5, p6, p7, p8, p9) end

---Undocumented. Native at 0x00504470
---@param p1 any
---@param p2 string
---@param p3 string
function RenderCustomSetLabel(p1, p2, p3) end

---Undocumented. Native at 0x00504ad0
---@param p1 any
---@param p2 string
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 number
---@param p7 number
---@param p8 number
---@param p9? number
function RenderCustomSetObjectTransform(p1, p2, p3, p4, p5, p6, p7, p8, p9) end

---Undocumented. Native at 0x00504500
---@param p1 any
---@param p2 string
---@param p3 string
function RenderCustomSetTexture(p1, p2, p3) end

---Undocumented. Native at 0x00505be0
---@param p1 any
---@param p2 string
---@param p3 string
---@param p4? number
function RenderCustomShowNIF(p1, p2, p3, p4) end

---Undocumented. Native at 0x00505b30
---@param p1 any
---@param p2 string
---@param p3 Alias
---@param p4? number
function RenderCustomShowObject(p1, p2, p3, p4) end

---Undocumented. Native at 0x00505a80
---@param p1 any
---@param p2 string
---@param p3 Alias
---@param p4? number
function RenderCustomShowSim(p1, p2, p3, p4) end

---Undocumented. Native at 0x0044ef70
---@param p1 number
---@param p2 Alias
function ResetAchievementProgress(p1, p2) end

---Undocumented. Native at 0x0070d3b0, GuildGameScriptBinding.cpp:20299
---@param p1 string
function ResolveLabel(p1) end

---Undocumented. Native at 0x007106d0, GuildGameScriptBinding.cpp:8355
---@param p1 string
---@param p2? number
---@param p3? number
function RollPoolName(p1, p2, p3) end

---Undocumented. Native at 0x0070afb0, GuildGameScriptBinding.cpp:18630
---@param p1 Alias
---@param p2? Alias
function RoomLockForCutscene(p1, p2) end

---Undocumented. Native at 0x00450ad0
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function SaveAllConfig(...) end

---Undocumented. Native at 0x00705e70, GuildGameScriptBinding.cpp:13763
---@param p1 number
---@param p2 Alias
---@param p3 Alias
---@param p4 string
function ScenarioCreateCart(p1, p2, p3, p4) end

---Undocumented. Native at 0x0070d8e0, GuildGameScriptBinding.cpp:543
---@param p1 Alias
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5? number
---@param p6? number
---@param p7? number
---@param p8 string
---@param p9? string
function ScenarioFindPosition(p1, p2, p3, p4, p5, p6, p7, p8, p9) end

---Undocumented. Native at 0x007099e0, GuildGameScriptBinding.cpp:16939
---@param p1? number
---@param p2? number
---@param p3? number
---@param p4? number
---@param p5? number
function ScenarioGetBuildingCount(p1, p2, p3, p4, p5) end

---Undocumented. Native at 0x006f70c0, GuildGameScriptBinding.cpp:1697
---@param p1 string
function ScenarioGetImperialCapital(p1) end

---Undocumented. Native at 0x006f7020, GuildGameScriptBinding.cpp:1683
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function ScenarioGetImperialCapitalId(...) end

---Undocumented. Native at 0x006f7290, GuildGameScriptBinding.cpp:1884
---@param p1 number
function ScenarioGetItemIdByNumber(p1) end

---Undocumented. Native at 0x006f7250, GuildGameScriptBinding.cpp:1869
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function ScenarioGetItemIdCount(...) end

---Undocumented. Native at 0x006f6ec0, GuildGameScriptBinding.cpp:1574
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function ScenarioGetKontorGoodCount(...) end

---Undocumented. Native at 0x006f6f50, GuildGameScriptBinding.cpp:1593
---@param p1 number
function ScenarioGetKontorGoodInfo(p1) end

---Undocumented. Native at 0x006f7190, GuildGameScriptBinding.cpp:1724
---@param p1 Alias
function ScenarioSetImperialCapital(p1) end

---Undocumented. Native at 0x00719a80, GuildGameScriptBinding.cpp:282
---@param p1 number
---@param p2 number
function SetArg(p1, p2) end

---Undocumented. Native at 0x00451960
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function SetConfigFloat(...) end

---Undocumented. Native at 0x00451480
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function SetConfigInt(...) end

---Undocumented. Native at 0x00451510
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function SetConfigString(...) end

---Undocumented. Native at 0x007034d0, GuildGameScriptBinding.cpp:11883
---@param p1 Alias
---@param p2 boolean
function SetEndlessMoney(p1, p2) end

---Undocumented. Native at 0x0044e4b0
---@param p1 number
---@param p2 string
---@param p3 number
function SetImportantPersonToSection(p1, p2, p3) end

---Undocumented. Native at 0x006ffcd0, GuildGameScriptBinding.cpp:8227
---@param p1 Alias
---@param p2 boolean
function SetInvisible(p1, p2) end

---Undocumented. Native at 0x00450270
---@param p1 Alias
function SetMenuState(p1) end

---Undocumented. Native at 0x00450390
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function SetPlayerName(...) end

---Undocumented. Native at 0x0070d320, GuildGameScriptBinding.cpp:20273
---@param p1 string
---@param p2 string
function SetRichPresence(p1, p2) end

---Undocumented. Native at 0x007190e0, GuildGameScriptBinding.cpp:5699
---@param p1 Alias
---@param p2 number
---@param p3? number
---@param p4? string
---@param p5? string
---@param p6? number
---@param p7? number
---@param p8? number
function SetWorkOfArtProvenance(p1, p2, p3, p4, p5, p6, p7, p8) end

---Undocumented. Native at 0x006fa6e0, GuildGameScriptBinding.cpp:4482
---@param p1 Alias
---@param p2 Alias
---@param p3? boolean
function SimCanBeHired(p1, p2, p3) end

---Undocumented. Native at 0x00705b60, GuildGameScriptBinding.cpp:13643
---@param p1 number
---@param p2 string
---@param p3? number
---@param p4? number
function SimCreateUnplaced(p1, p2, p3, p4) end

---Undocumented. Native at 0x006ffe20, GuildGameScriptBinding.cpp:8344
---@param p1 Alias
---@param p2 string
function SimGenerateName(p1, p2) end

---Undocumented. Native at 0x00701030, GuildGameScriptBinding.cpp:9709
---@param p1 Alias
---@param p2 number
---@param p3? string
function SimGetChildren(p1, p2, p3) end

---Undocumented. Native at 0x007010f0, GuildGameScriptBinding.cpp:9738
---@param p1 Alias
function SimGetChildrenCount(p1) end

---Undocumented. Native at 0x00710ab0, GuildGameScriptBinding.cpp:8934
---@param p1 Alias
---@param p2 string
function SimGetCourtingSim(p1, p2) end

---Undocumented. Native at 0x007112a0, GuildGameScriptBinding.cpp:9687
---@param p1 Alias
function SimGetDeadSpouseCount(p1) end

---Undocumented. Native at 0x00700850, GuildGameScriptBinding.cpp:8990
---@param p1 Alias
---@param p2 string
function SimGetLiaison(p1, p2) end

---Undocumented. Native at 0x00705630, GuildGameScriptBinding.cpp:13442
---@param p1 Alias
function SimGetServantDynastyId(p1) end

---Undocumented. Native at 0x006f9960, GuildGameScriptBinding.cpp:3701
---@param p1 Alias
function SimGetWeaponDamage(p1) end

---Undocumented. Native at 0x00710b50, GuildGameScriptBinding.cpp:8963
---@param p1 Alias
function SimIsCourting(p1) end

---Undocumented. Native at 0x007123f0, GuildGameScriptBinding.cpp:11049
---@param p1 Alias
---@param p2 number
function SimSetStartLevel(p1, p2) end

---Undocumented. Native at 0x005cfbd0
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function Sleep(...) end

---Undocumented. Native at 0x00709950, GuildGameScriptBinding.cpp:16797
---@param p1 Alias
---@param p2? number
function SneakVisActivate(p1, p2) end

---Undocumented. Native at 0x0070b930, GuildGameScriptBinding.cpp:19031
---@param p1 Alias
function SquadIsReady(p1) end

---Undocumented. Native at 0x004516a0
---@param p1 number
---@param p2 string
function StartSinglePlayerGame(p1, p2) end

---Undocumented. Native at 0x005cfd60
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function Stop(...) end

---Undocumented. Native at 0x00702ab0, GuildGameScriptBinding.cpp:11491
---@param p1 Alias
function StopAllAnimations(p1) end

---Undocumented. Native at 0x006ff080, GuildGameScriptBinding.cpp:7459
---@param p1 Alias
function StopProduction(p1) end

---Undocumented. Native at 0x0044d9b0
---@param p1 Alias
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 number
function TrialHUDSetSims(p1, p2, p3, p4, p5, p6) end

---Undocumented. Native at 0x0044daa0
---@param p1 Alias
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 number
---@param p7 number
function TrialHUDSetStatus(p1, p2, p3, p4, p5, p6, p7) end

---Undocumented. Native at 0x00459530
---@param p1 number
function UI_AttachCityListeners(p1) end

---Undocumented. Native at 0x00457d90
---@param p1 number
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 any
---@param p7 any
---@param p8 number
---@param p9 any
---@param p10 string
function UI_BringToFront(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) end

---Undocumented. Native at 0x0045b420
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function UI_CleanupAll(...) end

---Undocumented. Native at 0x00458c00
---@param p1 number
---@param p2 string
---@param p3 number
function UI_ComboBoxAddItem(p1, p2, p3) end

---Undocumented. Native at 0x00458e60
---@param p1 number
function UI_ComboBoxGetValue(p1) end

---Undocumented. Native at 0x00458f60
---@param p1 number
---@param p2 number
function UI_ComboBoxSetValue(p1, p2) end

---Undocumented. Native at 0x00457d80
---@param p1 number
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 any
---@param p7 any
---@param p8 number
---@param p9 any
---@param p10 string
function UI_CreateCheckbox(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) end

---Undocumented. Native at 0x00458700
---@param p1 number
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
function UI_CreateComboBox(p1, p2, p3, p4, p5) end

---Undocumented. Native at 0x00457c10
---@param p1 number
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 any
---@param p7 any
---@param p8 number
---@param p9 any
---@param p10 string
function UI_CreateLabel(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) end

---Undocumented. Native at 0x00459c10
---@param p1 number
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 number
---@param p7 string
---@param p8 number
---@param p9 number
---@param p10 string
---@param p11 string
---@param p12 number
function UI_CreateScrollBar(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12) end

---Undocumented. Native at 0x00457ff0
---@param p1 number
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 any
---@param p7 any
---@param p8 number
---@param p9 any
---@param p10 string
function UI_CreateSlider(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) end

---Undocumented. Native at 0x00457c20
---@param p1 number
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 any
---@param p7 any
---@param p8 number
---@param p9 any
---@param p10 string
function UI_CreateWindow(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) end

---Undocumented. Native at 0x00457c80
---@param p1 number
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 any
---@param p7 any
---@param p8 number
---@param p9 any
---@param p10 string
function UI_DestroyElement(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) end

---Undocumented. Native at 0x00459ba0
---@param p1 number
function UI_ExcludeFromHitTest(p1) end

---Undocumented. Native at 0x00450200
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function UI_GetCursorPos(...) end

---Undocumented. Native at 0x00457ca0
---@param p1 number
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 any
---@param p7 any
---@param p8 number
---@param p9 any
---@param p10 string
function UI_GetElementPosition(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) end

---Undocumented. Native at 0x004501f0
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function UI_GetScreenSize(...) end

---Undocumented. Native at 0x00451610
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function UI_GetSelectedCity(...) end

---Undocumented. Native at 0x00457cd0
---@param p1 number
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 any
---@param p7 any
---@param p8 number
---@param p9 any
---@param p10 string
function UI_GetSize(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) end

---Undocumented. Native at 0x00459020
---@param p1 number
function UI_GetSliderValue(p1) end

---Undocumented. Native at 0x00457d10
---@param p1 number
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 any
---@param p7 any
---@param p8 number
---@param p9 any
---@param p10 string
function UI_GetText(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) end

---Undocumented. Native at 0x00457d70
---@param p1 number
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 any
---@param p7 any
---@param p8 number
---@param p9 any
---@param p10 string
function UI_IsButtonPressed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) end

---Undocumented. Native at 0x00457db0
---@param p1 number
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 any
---@param p7 any
---@param p8 number
---@param p9 any
---@param p10 string
function UI_IsVisible(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) end

---Undocumented. Native at 0x004591f0
---@param p1 number
---@param p2 string
function UI_LoadMapGUI(p1, p2) end

---Undocumented. Native at 0x0045aab0
---@param p1 number
---@param p2 string
function UI_LoadSaveScreenshot(p1, p2) end

---Undocumented. Native at 0x00457ce0
---@param p1 number
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 any
---@param p7 any
---@param p8 number
---@param p9 any
---@param p10 string
function UI_SetAlpha(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) end

---Undocumented. Native at 0x00457d20
---@param p1 number
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 any
---@param p7 any
---@param p8 number
---@param p9 any
---@param p10 string
function UI_SetButtonColors(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) end

---Undocumented. Native at 0x00457d50
---@param p1 number
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 any
---@param p7 any
---@param p8 number
---@param p9 any
---@param p10 string
function UI_SetButtonHoverColor(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) end

---Undocumented. Native at 0x00457d40
---@param p1 number
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 any
---@param p7 any
---@param p8 number
---@param p9 any
---@param p10 string
function UI_SetButtonPressedColor(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) end

---Undocumented. Native at 0x00457d30
---@param p1 number
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 any
---@param p7 any
---@param p8 number
---@param p9 any
---@param p10 string
function UI_SetButtonReleasedColor(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) end

---Undocumented. Native at 0x00457cb0
---@param p1 number
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 any
---@param p7 any
---@param p8 number
---@param p9 any
---@param p10 string
function UI_SetButtonTexture(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) end

---Undocumented. Native at 0x004598c0
---@param p1 number
---@param p2 number
function UI_SetButtonWheelScroll(p1, p2) end

---Undocumented. Native at 0x00457110
---@param p1 number
function UI_SetCheckboxState(p1) end

---Undocumented. Native at 0x00457c70
---@param p1 number
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 any
---@param p7 any
---@param p8 number
---@param p9 any
---@param p10 string
function UI_SetColor(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) end

---Undocumented. Native at 0x00459a10
---@param p1 number
---@param p2 string
function UI_SetElementShader(p1, p2) end

---Undocumented. Native at 0x00459760
---@param p1 number
---@param p2 number
function UI_SetElementWheelScroll(p1, p2) end

---Undocumented. Native at 0x00457c40
---@param p1 number
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 any
---@param p7 any
---@param p8 number
---@param p9 any
---@param p10 string
function UI_SetEnabled(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) end

---Undocumented. Native at 0x00457cf0
---@param p1 number
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 any
---@param p7 any
---@param p8 number
---@param p9 any
---@param p10 string
function UI_SetFont(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) end

---Undocumented. Native at 0x00457d00
---@param p1 number
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 any
---@param p7 any
---@param p8 number
---@param p9 any
---@param p10 string
function UI_SetFontColor(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) end

---Undocumented. Native at 0x00456130
---@param p1 number
---@param p2 string
---@param p3 string
function UI_SetLabelAlignment(p1, p2, p3) end

---Undocumented. Native at 0x0045a9b0
---@param p1 number
function UI_SetMapFile(p1) end

---Undocumented. Native at 0x00457dc0
---@param p1 number
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 any
---@param p7 any
---@param p8 number
---@param p9 any
---@param p10 string
function UI_SetName(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) end

---Undocumented. Native at 0x00457c90
---@param p1 number
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 any
---@param p7 any
---@param p8 number
---@param p9 any
---@param p10 string
function UI_SetOnClick(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) end

---Undocumented. Native at 0x00457c50
---@param p1 number
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 any
---@param p7 any
---@param p8 number
---@param p9 any
---@param p10 string
function UI_SetPosition(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) end

---Undocumented. Native at 0x0045a6f0
---@param p1 number
---@param p2 number
---@param p3 number
function UI_SetScrollBarRange(p1, p2, p3) end

---Undocumented. Native at 0x00459ad0
---@param p1 number
function UI_SetShaderColor(p1) end

---Undocumented. Native at 0x00457cc0
---@param p1 number
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 any
---@param p7 any
---@param p8 number
---@param p9 any
---@param p10 string
function UI_SetSize(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) end

---Undocumented. Native at 0x00459120
---@param p1 number
---@param p2 string
function UI_SetSliderValue(p1, p2) end

---Undocumented. Native at 0x00457c60
---@param p1 number
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 any
---@param p7 any
---@param p8 number
---@param p9 any
---@param p10 string
function UI_SetText(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) end

---Undocumented. Native at 0x00456370
---@param p1 number
---@param p2 string
function UI_SetTextAlignment(p1, p2) end

---Undocumented. Native at 0x00457da0
---@param p1 number
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 any
---@param p7 any
---@param p8 number
---@param p9 any
---@param p10 string
function UI_SetTexture(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) end

---Undocumented. Native at 0x00457c30
---@param p1 number
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 any
---@param p7 any
---@param p8 number
---@param p9 any
---@param p10 string
function UI_SetVisible(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) end

---Undocumented. Native at 0x00457d60
---@param p1 number
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 any
---@param p7 any
---@param p8 number
---@param p9 any
---@param p10 string
function UI_SetupDefaultButton(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) end

---Undocumented. Native at 0x00456bf0
---@param p1 number
---@param p2 string
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 string
---@param p7 number
---@param p8 number
---@param p9 number
---@param p10 number
---@param p11 number
---@param p12 number
function UI_StyleMenuButton(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12) end

---Undocumented. Native at 0x004582f0
---@param p1 number
---@param p2 number
---@param p3 number
---@param p4 string
---@param p5 string
---@param p6 number
function UI_StyleSlider(p1, p2, p3, p4, p5, p6) end

---Undocumented. Native at 0x004571f0
---@param p1 number
function UI_ToggleCheckbox(p1) end

---Undocumented. Native at 0x00718810
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function UnloadShipCrew(...) end

---Undocumented. Native at 0x0070d150, GuildGameScriptBinding.cpp:20190
---@param p1 string
function UnlockAchievement(p1) end

---Undocumented. Native at 0x007157f0, GuildGameScriptBinding.cpp:20140
---@param p1 Alias
function Unmount(p1) end

---Undocumented. Native at 0x0044eaa0
---@param p1 number
---@param p2 number
---@param p3 Alias
function UpdateAchievementProgress(p1, p2, p3) end

---Undocumented. Native at 0x0070d240, GuildGameScriptBinding.cpp:20231
---@param p1 string
---@param p2 number
function UpdateStat(p1, p2) end

---Undocumented. Native at 0x006fa1e0, GuildGameScriptBinding.cpp:4183
---@param p1 Alias
function VehicleChangeModel(p1) end

---Undocumented. Native at 0x006fa2d0, GuildGameScriptBinding.cpp:4206
---@param p1 Alias
function VehicleGetModelName(p1) end

---Undocumented. Native at 0x006f81b0, GuildGameScriptBinding.cpp:2780
---@param p1 Alias
function VoiceIsMicActiveOn(p1) end

---Undocumented. Native at 0x006f8120, GuildGameScriptBinding.cpp:2761
---@param p1 Alias
function VoiceToggleMic(p1) end

---Undocumented. Native at 0x005cfcb0
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function WaitForMessage(...) end

---Undocumented. Native at 0x0044dba0
---@param p1 Alias
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
function WeddingHUDSetSims(p1, p2, p3, p4, p5) end

---Undocumented. Native at 0x0044dc70
---@param p1 Alias
---@param p2 number
---@param p3 number
---@param p4 number
---@param p5 number
---@param p6 number
function WeddingHUDSetStatus(p1, p2, p3, p4, p5, p6) end

---Undocumented. Native at 0x0088d0c0
---@param p1 any
---@param p2 number
function __add(p1, p2) end

---Undocumented. Native at 0x0088d310
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function __div(...) end

---Undocumented. Native at 0x0088d370
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function __eq(...) end

---Undocumented. Native at 0x0088d390
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function __gc(...) end

---Undocumented. Native at 0x0088d350
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function __le(...) end

---Undocumented. Native at 0x0088d330
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function __lt(...) end

---Undocumented. Native at 0x0088d2f0
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function __mul(...) end

---Undocumented. Native at 0x0088cca0
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function __newindex(...) end

---Undocumented. Native at 0x0088d2d0
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function __sub(...) end

---Undocumented. Native at 0x0088bbd0
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function cast(...) end

---Undocumented. Native at 0x008228b0
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function ipairs(...) end

---Undocumented. Native at 0x005cbb90
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function len(...) end

---Undocumented. Native at 0x00825e90
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function math(...) end

---Undocumented. Native at 0x00822dd0
---@param p1 Alias
function newproxy(p1) end

---Undocumented. Native at 0x00822830
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function pairs(...) end

---Undocumented. Native at 0x0088c0e0
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function releaseownership(...) end

---Undocumented. Native at 0x00825700
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function string(...) end

---Undocumented. Native at 0x00823c10
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function table(...) end

---Undocumented. Native at 0x0088bbb0
---Parameters not recoverable; accepts anything rather than
---claiming it takes none.
---@param ... any
function takeownership(...) end
